### ISSUE TITLE
Can't set headers after they are sent.

### ISSUE THREAD

**Issue by yoshuawuyts** [hughsk/watchify-request#3]
Every once in a blue moon the process crashes. Not sure what's causing it, but suspect it's some sort of race condition. Pasting it in here for reference:

```
  <-- GET /style.css                                                                            
  --> GET /style.css 200 7ms -
  <-- GET /bundle.js
  --> GET /bundle.js 404 2ms -
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:314:11)
    at handler (/Users/yoshuawuyts/src/yw/finfin/api-assets/node_modules/koa-watchify/node_modules/watch
fy-request/index.js:38:9)
    at EventEmitter.<anonymous> (/Users/yoshuawuyts/src/yw/finfin/api-assets/node_modules/koa-watchify/n
de_modules/watchify-request/index.js:32:16)
    at EventEmitter.g (/Users/yoshuawuyts/src/yw/finfin/api-assets/node_modules/koa-watchify/node_module
/watchify-request/node_modules/events/events.js:169:16)
    at EventEmitter.emit (/Users/yoshuawuyts/src/yw/finfin/api-assets/node_modules/koa-watchify/node_mod
les/watchify-request/node_modules/events/events.js:80:17)
    at BufferList._callback (/Users/yoshuawuyts/src/yw/finfin/api-assets/node_modules/koa-watchify/node_
odules/watchify-request/index.js:22:15)
    at BufferList.end (/Users/yoshuawuyts/src/yw/finfin/api-assets/node_modules/koa-watchify/node_module
/watchify-request/node_modules/bl/bl.js:78:10)
    at Labeled.onend (/Users/yoshuawuyts/src/yw/finfin/api-assets/node_modules/browserify/node_modules/r
adable-stream/lib/_stream_readable.js:537:10)
    at Labeled.g (events.js:257:16)
    at emitNone (events.js:72:20)
    at Labeled.emit (events.js:163:7)
```

**Comment by yoshuawuyts** [comment]
Also as a note, this was used from within `koa-watchify` so it may very well be possible that I'm screwing up on my side. Teehee, will close if somehow I don't run into this anymore.

**Comment by yoshuawuyts** [comment]
Also as a note, this was used from within `koa-watchify` so it may very well be possible that I'm screwing up on my side. Teehee, will close if somehow I don't run into this anymore.

**Comment by yoshuawuyts** [comment]
Reckon I was screwing up. Closing.
